version: '3.7'
services:

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=8EvlcUciChlyefOVedot
      - MYSQL_DATABASE=tutorialdjango
    ports:
      - "9306:3306"
    networks:
      - network1

  api:
    build:
      context: ./backend
      dockerfile: docker/docker_files/Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - network1

  app:
    build:
      context: .
      dockerfile: backend/docker/docker_files/Dockerfile_app
    depends_on:
      - db
    platform: linux/arm64
    restart: unless-stopped
    ports:
      - 6000:6000
    networks:
      - network1

networks:
  network1:
    name: myNetwork
    external: true

